// <auto-generated />
using System;
using GymProjectBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymProjectBackend.Migrations
{
    [DbContext(typeof(GymAppDbContext))]
    [Migration("20250903155032_AddingIDFieldToRoutineExercises")]
    partial class AddingIDFieldToRoutineExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymProjectBackend.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4921f63-a4f4-4771-944b-d83aa412990f"),
                            Description = "Works upper chest and shoulders; strengthens pectoral muscles.",
                            Name = "45° Incline Barbell Press"
                        },
                        new
                        {
                            Id = new Guid("7258c531-e5e6-4381-ac39-bef8e172abb3"),
                            Description = "Targets chest muscles; enhances muscle definition.",
                            Name = "Cable Crossover Ladder"
                        },
                        new
                        {
                            Id = new Guid("3b688d62-81ef-47dc-a3fe-d7d171f048f9"),
                            Description = "Strengthens back and biceps; improves upper body strength.",
                            Name = "Wide-Grip Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("481ea5b5-3563-4dda-9c94-5f0b497afc50"),
                            Description = "Focuses on shoulder deltoids; builds shoulder stability.",
                            Name = "High-Cable Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("1a44675c-7cff-4029-85ce-3e8520bf7a08"),
                            Description = "Works upper back; improves rowing strength.",
                            Name = "Pendlay Deficit Row"
                        },
                        new
                        {
                            Id = new Guid("60573d49-fa8b-43da-898a-27e9b3e269a5"),
                            Description = "Targets triceps; increases arm strength.",
                            Name = "Overhead Cable Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("9d34005b-0b74-4eb4-88d2-451418918e0b"),
                            Description = "Biceps focused curl; builds arm muscle mass.",
                            Name = "Bayesian Cable Curl"
                        },
                        new
                        {
                            Id = new Guid("c3cfa0ab-db58-41bc-8789-ffc5b30c175c"),
                            Description = "Works hamstrings; strengthens posterior leg muscles.",
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("9589df47-1ef3-472c-9cdf-bc3f270141c0"),
                            Description = "Targets quadriceps and glutes; improves leg power.",
                            Name = "Smith Machine Squat"
                        },
                        new
                        {
                            Id = new Guid("8e2b6a1c-75d0-4b65-a2f0-45f35a22e316"),
                            Description = "Works hamstrings and lower back; enhances stability.",
                            Name = "Barbell RDL"
                        },
                        new
                        {
                            Id = new Guid("107e847a-a9e3-4aad-ae72-abcac5276407"),
                            Description = "Targets quadriceps; improves knee extension strength.",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = new Guid("9e504cc8-5ea0-48bf-9903-31e256cdcd4d"),
                            Description = "Works calf muscles; builds lower leg strength.",
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("586619af-1eeb-44d8-91b8-3effa260dbeb"),
                            Description = "Targets abdominal muscles; improves core stability.",
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = new Guid("d3a1f831-9533-4284-af53-5de73a29b5e6"),
                            Description = "Strengthens latissimus dorsi and arms; improves back width.",
                            Name = "Neutral-Grip Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("e5cad7d1-1b2d-4a09-ac6e-d37dcfb8915b"),
                            Description = "Focuses on middle back; builds rowing muscles.",
                            Name = "Chest-Supported Machine Row"
                        },
                        new
                        {
                            Id = new Guid("917aa842-c9f8-49fb-92e0-456a9c74abae"),
                            Description = "Works back and biceps; enhances pulling power.",
                            Name = "Neutral-Grip Seated Cable Row"
                        },
                        new
                        {
                            Id = new Guid("b99471a5-aea1-4a68-a6a2-85b155877503"),
                            Description = "Targets rear deltoids; improves shoulder posture.",
                            Name = "1-Arm 45° Cable Rear Delt Flye"
                        },
                        new
                        {
                            Id = new Guid("f3d041ea-4be3-4917-b6ac-ff083d6f8c05"),
                            Description = "Strengthens trapezius muscles; improves upper back.",
                            Name = "Machine Shrug"
                        },
                        new
                        {
                            Id = new Guid("eb4f475b-353e-4105-87d5-fce442c0f30e"),
                            Description = "Biceps strengthening exercise; builds arm bulk.",
                            Name = "EZ-Bar Curl"
                        },
                        new
                        {
                            Id = new Guid("149d052f-3c6f-4bfb-9d9a-7f05920afc1f"),
                            Description = "Isolates biceps; enhances arm definition.",
                            Name = "Machine Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("40fa391d-30b3-4683-b4e9-2287127111df"),
                            Description = "Works chest, shoulders, and triceps; builds upper body strength.",
                            Name = "Barbell Bench Press"
                        },
                        new
                        {
                            Id = new Guid("2341500d-a031-4803-a3fc-3ae24c6c3662"),
                            Description = "Targets shoulder muscles; improves overhead strength.",
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("3da9c379-9fa9-4f0c-93db-7074289254a5"),
                            Description = "Focuses on chest; enhances muscle control.",
                            Name = "Bottom-Half DB Flye"
                        },
                        new
                        {
                            Id = new Guid("dbcf9322-65a8-4c5a-8426-dec86f58e937"),
                            Description = "Triceps isolation; increases arm muscle tone.",
                            Name = "Cable Triceps Kickback"
                        },
                        new
                        {
                            Id = new Guid("c8b2002c-8619-4143-820d-1a0e91a51a2d"),
                            Description = "Targets lower abs; improves core strength.",
                            Name = "Roman Chair Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("a185c69e-302c-40ac-b194-16547413515b"),
                            Description = "Works legs and glutes; increases leg power.",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = new Guid("3b94ecc8-e8d6-40de-bc0c-be8afbd79f02"),
                            Description = "Targets hamstrings; improves knee flexion.",
                            Name = "Seated Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("d615e2cc-99eb-4227-805b-a3dd834b732d"),
                            Description = "Works quads and glutes; enhances balance.",
                            Name = "DB Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = new Guid("84e2a93d-bdf4-4e88-826d-7d0453bd82b6"),
                            Description = "Targets inner thigh muscles; improves hip stability.",
                            Name = "Machine Hip Adduction"
                        },
                        new
                        {
                            Id = new Guid("c3324199-e791-48bb-9b79-84e794ab3530"),
                            Description = "Works outer thigh muscles; enhances hip strength.",
                            Name = "Machine Hip Abduction"
                        },
                        new
                        {
                            Id = new Guid("42052304-e86b-41be-8382-080ce288b853"),
                            Description = "Biceps focused cable curl; builds arm strength.",
                            Name = "EZ-Bar Cable Curl"
                        });
                });

            modelBuilder.Entity("GymProjectBackend.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.RoutineExercises", b =>
                {
                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Reps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("RoutineId", "ExerciseId", "Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("RoutineExercises");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.Routine", b =>
                {
                    b.HasOne("GymProjectBackend.Entities.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.RoutineExercises", b =>
                {
                    b.HasOne("GymProjectBackend.Entities.Exercise", "Exercise")
                        .WithMany("routineExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProjectBackend.Entities.Routine", "Routine")
                        .WithMany("routineExercises")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.Exercise", b =>
                {
                    b.Navigation("routineExercises");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.Routine", b =>
                {
                    b.Navigation("routineExercises");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.User", b =>
                {
                    b.Navigation("Routines");
                });
#pragma warning restore 612, 618
        }
    }
}
