// <auto-generated />
using System;
using GymProjectBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymProjectBackend.Migrations
{
    [DbContext(typeof(GymAppDbContext))]
    [Migration("20250902005539_SeedingExerciseData")]
    partial class SeedingExerciseData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymProjectBackend.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d450388f-b618-4bff-8f7e-93057e3f126d"),
                            Description = "Works upper chest and shoulders; strengthens pectoral muscles.",
                            Name = "45° Incline Barbell Press"
                        },
                        new
                        {
                            Id = new Guid("bdee0ca8-b85d-467d-a321-868562bccb7e"),
                            Description = "Targets chest muscles; enhances muscle definition.",
                            Name = "Cable Crossover Ladder"
                        },
                        new
                        {
                            Id = new Guid("77b3f3ed-3d84-43ee-b825-b4196fd65fb6"),
                            Description = "Strengthens back and biceps; improves upper body strength.",
                            Name = "Wide-Grip Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("5f3ea923-4f7e-43ba-8c72-a9e5fa1d0c35"),
                            Description = "Focuses on shoulder deltoids; builds shoulder stability.",
                            Name = "High-Cable Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("19ed1d82-2e4f-454a-868c-7a21392eeba0"),
                            Description = "Works upper back; improves rowing strength.",
                            Name = "Pendlay Deficit Row"
                        },
                        new
                        {
                            Id = new Guid("44a34dfa-f3b6-4ee2-b11a-77ad2a996c6c"),
                            Description = "Targets triceps; increases arm strength.",
                            Name = "Overhead Cable Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("3efde5b5-224d-4247-b3fc-256975550007"),
                            Description = "Biceps focused curl; builds arm muscle mass.",
                            Name = "Bayesian Cable Curl"
                        },
                        new
                        {
                            Id = new Guid("a725385c-fb51-474a-8918-a4d6655560f8"),
                            Description = "Works hamstrings; strengthens posterior leg muscles.",
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("530e99af-b707-4300-96e2-2ebd29568561"),
                            Description = "Targets quadriceps and glutes; improves leg power.",
                            Name = "Smith Machine Squat"
                        },
                        new
                        {
                            Id = new Guid("fc289eaf-67fa-42fd-b924-7a891bb9ecb0"),
                            Description = "Works hamstrings and lower back; enhances stability.",
                            Name = "Barbell RDL"
                        },
                        new
                        {
                            Id = new Guid("731c2f7a-d0f9-4e9b-a475-dd8378c961bb"),
                            Description = "Targets quadriceps; improves knee extension strength.",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = new Guid("7df68621-8af0-458c-a406-26bcbd5e6a2f"),
                            Description = "Works calf muscles; builds lower leg strength.",
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("6d29f811-26cc-4f4b-84b2-cf762dabbea6"),
                            Description = "Targets abdominal muscles; improves core stability.",
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = new Guid("cafec9aa-0b10-4bd1-a3e6-5c4d906e9312"),
                            Description = "Strengthens latissimus dorsi and arms; improves back width.",
                            Name = "Neutral-Grip Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("5b524366-b936-45d7-81bc-f45b44d7aa84"),
                            Description = "Focuses on middle back; builds rowing muscles.",
                            Name = "Chest-Supported Machine Row"
                        },
                        new
                        {
                            Id = new Guid("64f94f80-4273-4448-b466-101c7f93911c"),
                            Description = "Works back and biceps; enhances pulling power.",
                            Name = "Neutral-Grip Seated Cable Row"
                        },
                        new
                        {
                            Id = new Guid("89b5698a-c784-48f8-87cd-a3238146c7e6"),
                            Description = "Targets rear deltoids; improves shoulder posture.",
                            Name = "1-Arm 45° Cable Rear Delt Flye"
                        },
                        new
                        {
                            Id = new Guid("00b12ad3-d154-4d1d-a12a-4a3bad0013cf"),
                            Description = "Strengthens trapezius muscles; improves upper back.",
                            Name = "Machine Shrug"
                        },
                        new
                        {
                            Id = new Guid("c47064a8-f6bf-41c3-b185-4835d431ab6e"),
                            Description = "Biceps strengthening exercise; builds arm bulk.",
                            Name = "EZ-Bar Curl"
                        },
                        new
                        {
                            Id = new Guid("dcb4352f-96d5-44ae-8306-a7bc79af29d9"),
                            Description = "Isolates biceps; enhances arm definition.",
                            Name = "Machine Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("db3ee553-d9b3-49ec-86ad-4bda1b73089a"),
                            Description = "Works chest, shoulders, and triceps; builds upper body strength.",
                            Name = "Barbell Bench Press"
                        },
                        new
                        {
                            Id = new Guid("85dde610-fcf4-4257-bf79-7536ce9ef51e"),
                            Description = "Targets shoulder muscles; improves overhead strength.",
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("ffcb3187-9f9f-4b68-9274-75c01c71b466"),
                            Description = "Focuses on chest; enhances muscle control.",
                            Name = "Bottom-Half DB Flye"
                        },
                        new
                        {
                            Id = new Guid("7c5574c3-9af0-4e51-972d-c8b505ee2f37"),
                            Description = "Triceps isolation; increases arm muscle tone.",
                            Name = "Cable Triceps Kickback"
                        },
                        new
                        {
                            Id = new Guid("fc347390-1b3f-474d-831f-de4d328aea74"),
                            Description = "Targets lower abs; improves core strength.",
                            Name = "Roman Chair Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("fe503335-d0c9-4852-a0c9-7740edbf2529"),
                            Description = "Works legs and glutes; increases leg power.",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = new Guid("5c6e3644-55d4-40c8-a622-60937e6d1f1f"),
                            Description = "Targets hamstrings; improves knee flexion.",
                            Name = "Seated Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("acc12894-9671-4cb9-8d1b-03d1f2142334"),
                            Description = "Works quads and glutes; enhances balance.",
                            Name = "DB Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = new Guid("83377183-2181-41b0-a7a4-4997e91fefba"),
                            Description = "Targets inner thigh muscles; improves hip stability.",
                            Name = "Machine Hip Adduction"
                        },
                        new
                        {
                            Id = new Guid("33d2e640-5ec6-404d-8a98-e8bac12b1d0e"),
                            Description = "Works outer thigh muscles; enhances hip strength.",
                            Name = "Machine Hip Abduction"
                        },
                        new
                        {
                            Id = new Guid("9b83eca7-d801-461e-8828-01af82713e44"),
                            Description = "Biceps focused cable curl; builds arm strength.",
                            Name = "EZ-Bar Cable Curl"
                        });
                });

            modelBuilder.Entity("GymProjectBackend.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.RoutineExercises", b =>
                {
                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("RoutineId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("RoutineExercises");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.Routine", b =>
                {
                    b.HasOne("GymProjectBackend.Entities.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.RoutineExercises", b =>
                {
                    b.HasOne("GymProjectBackend.Entities.Exercise", "Exercise")
                        .WithMany("routineExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProjectBackend.Entities.Routine", "Routine")
                        .WithMany("routineExercises")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.Exercise", b =>
                {
                    b.Navigation("routineExercises");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.Routine", b =>
                {
                    b.Navigation("routineExercises");
                });

            modelBuilder.Entity("GymProjectBackend.Entities.User", b =>
                {
                    b.Navigation("Routines");
                });
#pragma warning restore 612, 618
        }
    }
}
